import { createApplication } from "@specific-dev/framework";
import * as appSchema from './schema/schema.js';
import * as authSchema from './schema/auth-schema.js';

const schema = { ...appSchema, ...authSchema };
const app = await createApplication(schema);

const questions = [
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Dacă x² - 5x + 6 = 0, care sunt soluțiile ecuației?',
    option_a: 'x₁=2, x₂=3',
    option_b: 'x₁=-2, x₂=-3',
    option_c: 'x₁=1, x₂=6',
    option_d: 'x₁=-1, x₂=-6',
    correct_option: 'a',
    explanation: 'Δ = 25 - 24 = 1; x = (5±1)/2, deci x₁=3, x₂=2.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'ușor',
    text: 'Care este valoarea expresiei 2³ + 3²?',
    option_a: '13',
    option_b: '17',
    option_c: '15',
    option_d: '19',
    correct_option: 'b',
    explanation: '2³=8, 3²=9, deci 8+9=17.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Într-un triunghi dreptunghic, catetele sunt 3 cm și 4 cm. Cât măsoară ipotenuza?',
    option_a: '5 cm',
    option_b: '6 cm',
    option_c: '7 cm',
    option_d: '√7 cm',
    correct_option: 'a',
    explanation: 'Teorema lui Pitagora: c²=3²+4²=9+16=25, deci c=5 cm.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Simplificați fracția (x²-4)/(x-2) pentru x≠2.',
    option_a: 'x-2',
    option_b: 'x+2',
    option_c: 'x²+2',
    option_d: '2x',
    correct_option: 'b',
    explanation: 'x²-4=(x-2)(x+2), deci (x-2)(x+2)/(x-2)=x+2.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Aria unui cerc cu raza r=5 cm este:',
    option_a: '10π cm²',
    option_b: '25π cm²',
    option_c: '5π cm²',
    option_d: '50π cm²',
    correct_option: 'b',
    explanation: 'A=πr²=π·25=25π cm².',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'ușor',
    text: 'Care este produsul (a+b)(a-b)?',
    option_a: 'a²+b²',
    option_b: 'a²-2ab+b²',
    option_c: 'a²-b²',
    option_d: 'a²+2ab+b²',
    correct_option: 'c',
    explanation: 'Formula diferenței de pătrate: (a+b)(a-b)=a²-b².',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'dificil',
    text: 'Rezolvați sistemul: x+y=7 și x-y=3. Care este valoarea lui x·y?',
    option_a: '8',
    option_b: '10',
    option_c: '12',
    option_d: '6',
    correct_option: 'b',
    explanation: 'x=(7+3)/2=5, y=(7-3)/2=2, deci x·y=10.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Suma unghiurilor interioare ale unui hexagon convex este:',
    option_a: '540°',
    option_b: '720°',
    option_c: '900°',
    option_d: '360°',
    correct_option: 'b',
    explanation: 'Suma unghiurilor unui poligon cu n laturi = (n-2)·180°. Pentru n=6: 4·180°=720°.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'ușor',
    text: 'Care este valoarea lui √144?',
    option_a: '11',
    option_b: '13',
    option_c: '12',
    option_d: '14',
    correct_option: 'c',
    explanation: '12·12=144, deci √144=12.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Dacă 2x + 3 = 11, atunci x este egal cu:',
    option_a: '3',
    option_b: '4',
    option_c: '5',
    option_d: '6',
    correct_option: 'b',
    explanation: '2x=11-3=8, deci x=4.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Perimetrul unui pătrat cu latura de 7 cm este:',
    option_a: '14 cm',
    option_b: '21 cm',
    option_c: '28 cm',
    option_d: '49 cm',
    correct_option: 'c',
    explanation: 'P=4·l=4·7=28 cm.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'dificil',
    text: 'Care este soluția inecuației 3x - 7 > 2x + 1?',
    option_a: 'x > 6',
    option_b: 'x > 8',
    option_c: 'x < 8',
    option_d: 'x > -8',
    correct_option: 'b',
    explanation: '3x-2x > 1+7, deci x > 8.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Volumul unui cub cu latura a=3 cm este:',
    option_a: '9 cm³',
    option_b: '18 cm³',
    option_c: '27 cm³',
    option_d: '81 cm³',
    correct_option: 'c',
    explanation: 'V=a³=3³=27 cm³.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Factorizați expresia x² + 5x + 6.',
    option_a: '(x+1)(x+6)',
    option_b: '(x+2)(x+3)',
    option_c: '(x-2)(x-3)',
    option_d: '(x+2)(x-3)',
    correct_option: 'b',
    explanation: 'Căutăm a·b=6 și a+b=5: a=2, b=3. Deci (x+2)(x+3).',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'dificil',
    text: 'Într-un triunghi isoscel, unghiul de la vârf este 40°. Cât măsoară fiecare unghi de la bază?',
    option_a: '60°',
    option_b: '70°',
    option_c: '80°',
    option_d: '50°',
    correct_option: 'b',
    explanation: 'Suma unghiurilor=180°. Cele două unghiuri de la bază sunt egale: (180°-40°)/2=70°.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'ușor',
    text: 'Care este valoarea expresiei |−8| + |3|?',
    option_a: '5',
    option_b: '-5',
    option_c: '11',
    option_d: '-11',
    correct_option: 'c',
    explanation: '|−8|=8, |3|=3, deci 8+3=11.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Dacă f(x) = 2x² - 3x + 1, atunci f(2) este egal cu:',
    option_a: '1',
    option_b: '2',
    option_c: '3',
    option_d: '4',
    correct_option: 'c',
    explanation: 'f(2)=2·4-3·2+1=8-6+1=3.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Aria unui triunghi cu baza b=8 cm și înălțimea h=5 cm este:',
    option_a: '13 cm²',
    option_b: '20 cm²',
    option_c: '40 cm²',
    option_d: '80 cm²',
    correct_option: 'b',
    explanation: 'A=(b·h)/2=(8·5)/2=20 cm².',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'dificil',
    text: 'Care este suma primilor 10 termeni ai progresiei aritmetice 2, 5, 8, 11, ...?',
    option_a: '120',
    option_b: '155',
    option_c: '140',
    option_d: '130',
    correct_option: 'b',
    explanation: 'a₁=2, d=3, a₁₀=2+9·3=29. Sₙ=n(a₁+aₙ)/2=10·31/2=155.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'dificil',
    text: 'Diagonala unui dreptunghi cu laturile 6 cm și 8 cm măsoară:',
    option_a: '10 cm',
    option_b: '12 cm',
    option_c: '14 cm',
    option_d: '√28 cm',
    correct_option: 'a',
    explanation: 'd=√(6²+8²)=√(36+64)=√100=10 cm.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'mediu',
    text: 'Câte soluții întregi are ecuația x² = 25?',
    option_a: '0',
    option_b: '1',
    option_c: '2',
    option_d: '4',
    correct_option: 'c',
    explanation: 'x²=25 ⟹ x=5 sau x=-5. Deci 2 soluții întregi.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'ușor',
    text: 'Care este cel mai mare divizor comun al numerelor 36 și 48?',
    option_a: '6',
    option_b: '12',
    option_c: '18',
    option_d: '24',
    correct_option: 'b',
    explanation: '36=2²·3², 48=2⁴·3. CMMD=2²·3=12.',
  },
  {
    subject: 'Matematică',
    chapter: 'Geometrie',
    difficulty: 'mediu',
    text: 'Circumferința unui cerc cu diametrul d=10 cm este:',
    option_a: '5π cm',
    option_b: '10π cm',
    option_c: '20π cm',
    option_d: '100π cm',
    correct_option: 'b',
    explanation: 'C=π·d=10π cm.',
  },
  {
    subject: 'Matematică',
    chapter: 'Algebră',
    difficulty: 'dificil',
    text: 'Dacă log₂(x) = 3, atunci x este egal cu:',
    option_a: '6',
    option_b: '9',
    option_c: '8',
    option_d: '12',
    correct_option: 'c',
    explanation: 'log₂(x)=3 ⟹ x=2³=8.',
  },
];

try {
  // Check if the table is empty
  const existingQuestions = await app.db.select().from(schema.questions);

  if (existingQuestions.length === 0) {
    app.logger.info({ count: questions.length }, 'Inserting seed questions');
    await app.db.insert(schema.questions).values(questions);
    app.logger.info({ count: questions.length }, 'Questions inserted successfully');
  } else {
    app.logger.info({ existingCount: existingQuestions.length }, 'Questions table is not empty, skipping seed');
  }

  process.exit(0);
} catch (error) {
  app.logger.error({ err: error }, 'Failed to seed questions');
  process.exit(1);
}
