import { createApplication } from "@specific-dev/framework";
import * as appSchema from './schema/schema.js';
import * as authSchema from './schema/auth-schema.js';

const schema = { ...appSchema, ...authSchema };
const app = await createApplication(schema);

const questions = [
  // ALGEBRĂ: Mulțimi și operații cu mulțimi (5 questions)
  {
    subject: 'Algebră',
    chapter: 'Mulțimi și operații cu mulțimi',
    difficulty: 'usor',
    text: 'Fie A = {1, 2, 3, 4} și B = {3, 4, 5, 6}. Care este A ∩ B?',
    option_a: '{1, 2, 3, 4, 5, 6}',
    option_b: '{3, 4}',
    option_c: '{1, 2}',
    option_d: '{5, 6}',
    correct_option: 'b',
    explanation: 'Intersecția A ∩ B conține elementele comune ambelor mulțimi: {3, 4}.',
  },
  {
    subject: 'Algebră',
    chapter: 'Mulțimi și operații cu mulțimi',
    difficulty: 'usor',
    text: 'Fie A = {1, 2, 3} și B = {2, 3, 4, 5}. Care este A ∪ B?',
    option_a: '{2, 3}',
    option_b: '{1, 4, 5}',
    option_c: '{1, 2, 3, 4, 5}',
    option_d: '{1, 2, 3, 4}',
    correct_option: 'c',
    explanation: 'Reuniunea A ∪ B conține toate elementele din A sau B: {1, 2, 3, 4, 5}.',
  },
  {
    subject: 'Algebră',
    chapter: 'Mulțimi și operații cu mulțimi',
    difficulty: 'mediu',
    text: 'Fie A = {x ∈ ℕ | x < 5} și B = {x ∈ ℕ | x este par și x ≤ 6}. Câte elemente are A \\ B?',
    option_a: '2',
    option_b: '3',
    option_c: '4',
    option_d: '1',
    correct_option: 'a',
    explanation: 'A = {0,1,2,3,4}, B = {0,2,4,6}. A \\ B = {1, 3}, deci are 2 elemente.',
  },
  {
    subject: 'Algebră',
    chapter: 'Mulțimi și operații cu mulțimi',
    difficulty: 'mediu',
    text: 'Dacă A ⊂ B și card(A) = 3, card(B) = 5, câte elemente are B \\ A?',
    option_a: '8',
    option_b: '3',
    option_c: '2',
    option_d: '15',
    correct_option: 'c',
    explanation: 'B \\ A conține elementele din B care nu sunt în A: card(B \\ A) = 5 − 3 = 2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Mulțimi și operații cu mulțimi',
    difficulty: 'dificil',
    text: 'Fie A = {1, 2, 3, 4, 5}. Câte submulțimi cu exact 3 elemente are mulțimea A?',
    option_a: '6',
    option_b: '10',
    option_c: '15',
    option_d: '8',
    correct_option: 'b',
    explanation: 'Numărul de submulțimi cu 3 elemente din 5 este C(5,3) = 5!/(3!·2!) = 10.',
  },

  // ALGEBRĂ: Numere reale și radicali (6 questions)
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'usor',
    text: 'Care este valoarea expresiei √48 − √27 + √3?',
    option_a: '4√3',
    option_b: '2√3',
    option_c: '√3',
    option_d: '6√3',
    correct_option: 'b',
    explanation: '√48 = 4√3, √27 = 3√3. Deci 4√3 − 3√3 + √3 = 2√3.',
  },
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'usor',
    text: 'Cât este (√5 + √3)(√5 − √3)?',
    option_a: '2',
    option_b: '8',
    option_c: '√2',
    option_d: '4',
    correct_option: 'a',
    explanation: 'Folosind formula (a+b)(a−b) = a²−b²: (√5)²−(√3)² = 5−3 = 2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'mediu',
    text: 'Simplificați expresia: (√6 + √2) / √2.',
    option_a: '√3 + 1',
    option_b: '√8',
    option_c: '√3',
    option_d: '2√3',
    correct_option: 'a',
    explanation: '(√6 + √2)/√2 = √6/√2 + √2/√2 = √3 + 1.',
  },
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'mediu',
    text: 'Care este partea întreagă a numărului √50?',
    option_a: '6',
    option_b: '7',
    option_c: '8',
    option_d: '5',
    correct_option: 'b',
    explanation: '7² = 49 < 50 < 64 = 8², deci √50 ∈ (7, 8), iar partea întreagă este 7.',
  },
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'mediu',
    text: 'Raționalizați numitorul fracției 1/(√3 − 1).',
    option_a: '(√3 + 1)/4',
    option_b: '(√3 − 1)/2',
    option_c: '(√3 + 1)/2',
    option_d: '(√3 + 1)/3',
    correct_option: 'c',
    explanation: 'Înmulțim cu conjugatul: 1·(√3+1)/((√3−1)(√3+1)) = (√3+1)/(3−1) = (√3+1)/2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Numere reale și radicali',
    difficulty: 'dificil',
    text: 'Dacă x = √2 + 1, cât este x² − 2x?',
    option_a: '1',
    option_b: '2',
    option_c: '√2',
    option_d: '0',
    correct_option: 'a',
    explanation: 'x² = (√2+1)² = 2+2√2+1 = 3+2√2. 2x = 2√2+2. x²−2x = 3+2√2−2√2−2 = 1.',
  },

  // ALGEBRĂ: Ecuații și inecuații (6 questions)
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'usor',
    text: 'Care este soluția ecuației 3x − 7 = 2x + 5?',
    option_a: 'x = 2',
    option_b: 'x = 12',
    option_c: 'x = −2',
    option_d: 'x = 6',
    correct_option: 'b',
    explanation: '3x − 2x = 5 + 7 → x = 12.',
  },
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'usor',
    text: 'Rezolvați inecuația 2x + 3 > 7.',
    option_a: 'x > 5',
    option_b: 'x < 2',
    option_c: 'x > 2',
    option_d: 'x ≥ 2',
    correct_option: 'c',
    explanation: '2x > 7 − 3 → 2x > 4 → x > 2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'mediu',
    text: 'Câte soluții reale are ecuația x² − 5x + 6 = 0?',
    option_a: 'Nicio soluție reală',
    option_b: 'O singură soluție',
    option_c: 'Două soluții reale distincte',
    option_d: 'Infinit de soluții',
    correct_option: 'c',
    explanation: 'Δ = 25 − 24 = 1 > 0, deci ecuația are două soluții reale distincte: x₁ = 2, x₂ = 3.',
  },
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'mediu',
    text: 'Care sunt soluțiile ecuației x² − 5x + 6 = 0?',
    option_a: 'x₁ = 1, x₂ = 6',
    option_b: 'x₁ = 2, x₂ = 3',
    option_c: 'x₁ = −2, x₂ = −3',
    option_d: 'x₁ = −1, x₂ = 6',
    correct_option: 'b',
    explanation: 'x² − 5x + 6 = (x−2)(x−3) = 0, deci x₁ = 2 și x₂ = 3.',
  },
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'mediu',
    text: 'Rezolvați ecuația |2x − 4| = 6.',
    option_a: 'x = 5 sau x = −1',
    option_b: 'x = 5 sau x = 1',
    option_c: 'x = 1 sau x = −5',
    option_d: 'x = −5 sau x = −1',
    correct_option: 'a',
    explanation: '|2x−4| = 6 → 2x−4 = 6 sau 2x−4 = −6 → x = 5 sau x = −1.',
  },
  {
    subject: 'Algebră',
    chapter: 'Ecuații și inecuații',
    difficulty: 'dificil',
    text: 'Suma soluțiilor ecuației 2x² − 6x + 4 = 0 este:',
    option_a: '3',
    option_b: '2',
    option_c: '−3',
    option_d: '6',
    correct_option: 'a',
    explanation: 'Prin relațiile lui Viète: x₁ + x₂ = −(−6)/2 = 3.',
  },

  // ALGEBRĂ: Sisteme de ecuații (4 questions)
  {
    subject: 'Algebră',
    chapter: 'Sisteme de ecuații',
    difficulty: 'mediu',
    text: 'Rezolvați sistemul: x + y = 7, x − y = 3. Care este valoarea lui x?',
    option_a: 'x = 2',
    option_b: 'x = 5',
    option_c: 'x = 4',
    option_d: 'x = 3',
    correct_option: 'b',
    explanation: 'Adunând ecuațiile: 2x = 10 → x = 5. Din prima: y = 7 − 5 = 2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Sisteme de ecuații',
    difficulty: 'mediu',
    text: 'Rezolvați sistemul: 2x + y = 8, x − y = 1. Care este valoarea lui y?',
    option_a: 'y = 1',
    option_b: 'y = 3',
    option_c: 'y = 2',
    option_d: 'y = 5',
    correct_option: 'c',
    explanation: 'Din a doua: x = y + 1. Substituind: 2(y+1) + y = 8 → 3y = 6 → y = 2.',
  },
  {
    subject: 'Algebră',
    chapter: 'Sisteme de ecuații',
    difficulty: 'dificil',
    text: 'Sistemul 3x − 2y = 5, 6x − 4y = 10 are:',
    option_a: 'O singură soluție',
    option_b: 'Nicio soluție',
    option_c: 'Infinit de soluții',
    option_d: 'Două soluții',
    correct_option: 'c',
    explanation: 'A doua ecuație este dublul primei, deci sistemul este compatibil nedeterminat (infinit de soluții).',
  },
  {
    subject: 'Algebră',
    chapter: 'Sisteme de ecuații',
    difficulty: 'dificil',
    text: 'Dacă sistemul x + 2y = 5, 2x + ky = 10 are infinit de soluții, atunci k este:',
    option_a: 'k = 1',
    option_b: 'k = 4',
    option_c: 'k = 2',
    option_d: 'k = 5',
    correct_option: 'b',
    explanation: 'Pentru infinit de soluții, a doua ecuație trebuie să fie multiplu al primei: 2x + 4y = 10. Deci k = 4.',
  },

  // ALGEBRĂ: Funcții (5 questions)
  {
    subject: 'Algebră',
    chapter: 'Funcții',
    difficulty: 'usor',
    text: 'Funcția f: ℝ → ℝ, f(x) = 2x − 3 este o funcție:',
    option_a: 'Pătratică',
    option_b: 'Liniară (afină)',
    option_c: 'Constantă',
    option_d: 'Exponențială',
    correct_option: 'b',
    explanation: 'f(x) = 2x − 3 este de forma ax + b cu a = 2 ≠ 0, deci este funcție liniară (afină).',
  },
  {
    subject: 'Algebră',
    chapter: 'Funcții',
    difficulty: 'usor',
    text: 'Care este valoarea lui f(3) dacă f(x) = x² − 2x + 1?',
    option_a: '4',
    option_b: '6',
    option_c: '2',
    option_d: '8',
    correct_option: 'a',
    explanation: 'f(3) = 9 − 6 + 1 = 4.',
  },
  {
    subject: 'Algebră',
    chapter: 'Funcții',
    difficulty: 'mediu',
    text: 'Funcția f(x) = x² − 4x + 3 are vârful parabolei în punctul:',
    option_a: '(2, −1)',
    option_b: '(−2, 1)',
    option_c: '(2, 1)',
    option_d: '(4, 3)',
    correct_option: 'a',
    explanation: 'Vârful are abscisa x_V = −b/(2a) = 4/2 = 2. f(2) = 4 − 8 + 3 = −1. Deci V(2, −1).',
  },
  {
    subject: 'Algebră',
    chapter: 'Funcții',
    difficulty: 'mediu',
    text: 'Graficul funcției f(x) = 3x − 6 intersectează axa Ox în punctul:',
    option_a: '(0, −6)',
    option_b: '(2, 0)',
    option_c: '(6, 0)',
    option_d: '(−2, 0)',
    correct_option: 'b',
    explanation: 'Intersecția cu Ox: f(x) = 0 → 3x − 6 = 0 → x = 2. Punctul este (2, 0).',
  },
  {
    subject: 'Algebră',
    chapter: 'Funcții',
    difficulty: 'dificil',
    text: 'Funcția f(x) = −x² + 4x − 3 are valoarea maximă:',
    option_a: '1',
    option_b: '3',
    option_c: '4',
    option_d: '−3',
    correct_option: 'a',
    explanation: 'a = −1 < 0, deci parabola are maxim. x_V = 4/2 = 2. f(2) = −4 + 8 − 3 = 1.',
  },

  // GEOMETRIE PLANĂ (8 questions)
  {
    subject: 'Geometrie',
    chapter: 'Triunghi',
    difficulty: 'usor',
    text: 'Într-un triunghi dreptunghic cu catetele 3 cm și 4 cm, ipotenuza are lungimea:',
    option_a: '7 cm',
    option_b: '5 cm',
    option_c: '√7 cm',
    option_d: '6 cm',
    correct_option: 'b',
    explanation: 'Prin teorema lui Pitagora: c² = 3² + 4² = 9 + 16 = 25, deci c = 5 cm.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Triunghi',
    difficulty: 'mediu',
    text: 'Suma unghiurilor unui triunghi este:',
    option_a: '90°',
    option_b: '360°',
    option_c: '270°',
    option_d: '180°',
    correct_option: 'd',
    explanation: 'Suma unghiurilor interioare ale oricărui triunghi este 180°.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Triunghi',
    difficulty: 'mediu',
    text: 'Într-un triunghi isoscel, unghiul de la vârf este 40°. Cât măsoară fiecare unghi de la bază?',
    option_a: '60°',
    option_b: '80°',
    option_c: '70°',
    option_d: '50°',
    correct_option: 'c',
    explanation: 'Suma unghiurilor = 180°. Cele două unghiuri de la bază sunt egale: (180° − 40°)/2 = 70°.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Triunghi',
    difficulty: 'dificil',
    text: 'Aria unui triunghi cu baza 8 cm și înălțimea corespunzătoare de 5 cm este:',
    option_a: '40 cm²',
    option_b: '13 cm²',
    option_c: '20 cm²',
    option_d: '16 cm²',
    correct_option: 'c',
    explanation: 'Aria = (baza × înălțimea) / 2 = (8 × 5) / 2 = 20 cm².',
  },
  {
    subject: 'Geometrie',
    chapter: 'Patrulater',
    difficulty: 'usor',
    text: 'Diagonalele unui romb sunt de 6 cm și 8 cm. Care este aria rombului?',
    option_a: '48 cm²',
    option_b: '14 cm²',
    option_c: '24 cm²',
    option_d: '28 cm²',
    correct_option: 'c',
    explanation: 'Aria rombului = (d₁ × d₂) / 2 = (6 × 8) / 2 = 24 cm².',
  },
  {
    subject: 'Geometrie',
    chapter: 'Patrulater',
    difficulty: 'mediu',
    text: 'Un dreptunghi are lungimea de 10 cm și lățimea de 6 cm. Cât este diagonala sa?',
    option_a: '8 cm',
    option_b: '16 cm',
    option_c: '4√34 cm',
    option_d: '2√34 cm',
    correct_option: 'd',
    explanation: 'Diagonala = √(10² + 6²) = √(100 + 36) = √136 = 2√34 cm.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Cerc',
    difficulty: 'mediu',
    text: 'Un cerc are raza de 5 cm. Care este aria sa? (π ≈ 3,14)',
    option_a: '31,4 cm²',
    option_b: '78,5 cm²',
    option_c: '15,7 cm²',
    option_d: '25π cm',
    correct_option: 'b',
    explanation: 'Aria = π·r² = π·25 ≈ 3,14 × 25 = 78,5 cm².',
  },
  {
    subject: 'Geometrie',
    chapter: 'Cerc',
    difficulty: 'dificil',
    text: 'Un arc de cerc cu raza 6 cm subîntinde un unghi la centru de 60°. Lungimea arcului este:',
    option_a: '2π cm',
    option_b: '6π cm',
    option_c: 'π cm',
    option_d: '3π cm',
    correct_option: 'a',
    explanation: 'Lungimea arcului = (unghi/360°) × 2πr = (60/360) × 2π × 6 = (1/6) × 12π = 2π cm.',
  },

  // GEOMETRIE ÎN SPAȚIU (6 questions)
  {
    subject: 'Geometrie',
    chapter: 'Geometrie în spațiu',
    difficulty: 'usor',
    text: 'Un cub cu latura de 3 cm are volumul:',
    option_a: '9 cm³',
    option_b: '27 cm³',
    option_c: '18 cm³',
    option_d: '54 cm³',
    correct_option: 'b',
    explanation: 'Volumul cubului = a³ = 3³ = 27 cm³.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Geometrie în spațiu',
    difficulty: 'mediu',
    text: 'O prismă dreaptă cu baza dreptunghi (4 cm × 3 cm) și înălțimea 5 cm are volumul:',
    option_a: '60 cm³',
    option_b: '120 cm³',
    option_c: '24 cm³',
    option_d: '35 cm³',
    correct_option: 'a',
    explanation: 'Volumul prismei = Aria bazei × înălțimea = (4 × 3) × 5 = 60 cm³.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Geometrie în spațiu',
    difficulty: 'mediu',
    text: 'Un cilindru cu raza bazei 3 cm și înălțimea 4 cm are volumul:',
    option_a: '12π cm³',
    option_b: '36π cm³',
    option_c: '24π cm³',
    option_d: '48π cm³',
    correct_option: 'b',
    explanation: 'Volumul cilindrului = π·r²·h = π·9·4 = 36π cm³.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Geometrie în spațiu',
    difficulty: 'mediu',
    text: 'O piramidă cu baza pătrată cu latura 6 cm și înălțimea 4 cm are volumul:',
    option_a: '144 cm³',
    option_b: '72 cm³',
    option_c: '48 cm³',
    option_d: '36 cm³',
    correct_option: 'c',
    explanation: 'Volumul piramidei = (1/3) × Aria bazei × înălțimea = (1/3) × 36 × 4 = 48 cm³.',
  },
  {
    subject: 'Geometrie',
    chapter: 'Geometrie în spațiu',
    difficulty: 'dificil',
    text: 'Un con cu raza bazei 3 cm și înălțimea 4 cm are volumul:',
    option_a: '12π cm³',
    option_b: '36π cm³',
    option_c: '4π cm³',
    option_d: '9π cm³',
    correct_option: 'a',
    explanation: 'Volumul conului = (1/3)·π·r²·h = (1/3)·π·9·4 = 12π cm³.',
  },
  {
    subject: 'Probabilități',
    chapter: 'Probabilități și statistică',
    difficulty: 'mediu',
    text: 'Se aruncă un zar echilibrat. Care este probabilitatea de a obține un număr par?',
    option_a: '1/6',
    option_b: '1/3',
    option_c: '2/3',
    option_d: '1/2',
    correct_option: 'd',
    explanation: 'Numerele pare pe un zar sunt {2, 4, 6}, deci 3 cazuri favorabile din 6 posibile: P = 3/6 = 1/2.',
  },
];

try {
  // Delete all existing questions atomically
  app.logger.info({}, 'Deleting all existing questions');
  await app.db.delete(schema.questions);

  // Insert all 40 new questions
  app.logger.info({ count: questions.length }, 'Inserting 40 seed questions');
  await app.db.insert(schema.questions).values(questions);
  app.logger.info({ count: questions.length }, 'Questions seeded successfully');

  process.exit(0);
} catch (error) {
  app.logger.error({ err: error }, 'Failed to seed questions');
  process.exit(1);
}
