import { createApplication } from "@specific-dev/framework";
import * as appSchema from './schema/schema.js';
import * as authSchema from './schema/auth-schema.js';

const schema = { ...appSchema, ...authSchema };
const app = await createApplication(schema);

const questions = [
  // ALGEBRA: Ecuații de gradul I (easy)
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul I',
    difficulty: 'easy',
    text: 'Rezolvați ecuația: 2x + 6 = 0',
    option_a: 'x = -3',
    option_b: 'x = 3',
    option_c: 'x = -6',
    option_d: 'x = 6',
    correct_option: 'a',
    explanation: 'Împărțim ambii membri la 2: x + 3 = 0, deci x = -3',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul I',
    difficulty: 'easy',
    text: 'Rezolvați ecuația: 3x - 9 = 0',
    option_a: 'x = 9',
    option_b: 'x = -3',
    option_c: 'x = 3',
    option_d: 'x = -9',
    correct_option: 'c',
    explanation: '3x = 9, deci x = 9/3 = 3',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul I',
    difficulty: 'medium',
    text: 'Rezolvați ecuația: 5x + 2 = 3x + 10',
    option_a: 'x = 4',
    option_b: 'x = -4',
    option_c: 'x = 6',
    option_d: 'x = 2',
    correct_option: 'a',
    explanation: '5x - 3x = 10 - 2, 2x = 8, x = 4',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul I',
    difficulty: 'medium',
    text: 'Rezolvați ecuația: 4(x - 1) = 2(x + 3)',
    option_a: 'x = 5',
    option_b: 'x = -5',
    option_c: 'x = 3',
    option_d: 'x = 7',
    correct_option: 'a',
    explanation: '4x - 4 = 2x + 6, 2x = 10, x = 5',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul I',
    difficulty: 'hard',
    text: 'Rezolvați ecuația: (x+2)/3 - (x-1)/2 = 1',
    option_a: 'x = -1',
    option_b: 'x = 1',
    option_c: 'x = 2',
    option_d: 'x = -2',
    correct_option: 'b',
    explanation: 'Înmulțim cu 6: 2(x+2) - 3(x-1) = 6, 2x+4-3x+3=6, -x+7=6, x=1',
  },

  // ALGEBRA: Ecuații de gradul II (medium/hard)
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul II',
    difficulty: 'easy',
    text: 'Rezolvați ecuația: x² - 9 = 0',
    option_a: 'x = ±3',
    option_b: 'x = 3',
    option_c: 'x = -3',
    option_d: 'x = ±9',
    correct_option: 'a',
    explanation: 'x² = 9, deci x = ±√9 = ±3',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul II',
    difficulty: 'medium',
    text: 'Rezolvați ecuația: x² - 5x + 6 = 0',
    option_a: 'x = 2 sau x = 3',
    option_b: 'x = -2 sau x = -3',
    option_c: 'x = 1 sau x = 6',
    option_d: 'x = 2 sau x = -3',
    correct_option: 'a',
    explanation: 'Δ = 25-24=1, x=(5±1)/2, x₁=3, x₂=2',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul II',
    difficulty: 'medium',
    text: 'Rezolvați ecuația: x² + 4x + 4 = 0',
    option_a: 'x = -2',
    option_b: 'x = 2',
    option_c: 'x = -4',
    option_d: 'x = 4',
    correct_option: 'a',
    explanation: '(x+2)² = 0, deci x = -2 (rădăcină dublă)',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul II',
    difficulty: 'hard',
    text: 'Rezolvați ecuația: 2x² - 7x + 3 = 0',
    option_a: 'x = 3 sau x = 1/2',
    option_b: 'x = -3 sau x = -1/2',
    option_c: 'x = 3 sau x = -1/2',
    option_d: 'x = 1 sau x = 3/2',
    correct_option: 'a',
    explanation: 'Δ = 49-24=25, x=(7±5)/4, x₁=3, x₂=1/2',
  },
  {
    subject: 'algebra',
    chapter: 'Ecuații de gradul II',
    difficulty: 'hard',
    text: 'Care este suma rădăcinilor ecuației 3x² - 12x + 9 = 0?',
    option_a: '4',
    option_b: '3',
    option_c: '6',
    option_d: '12',
    correct_option: 'a',
    explanation: 'Prin formula lui Viète: S = -b/a = 12/3 = 4',
  },

  // ALGEBRA: Sisteme de ecuații
  {
    subject: 'algebra',
    chapter: 'Sisteme de ecuații',
    difficulty: 'easy',
    text: 'Rezolvați sistemul: x + y = 5, x - y = 1',
    option_a: 'x=3, y=2',
    option_b: 'x=2, y=3',
    option_c: 'x=4, y=1',
    option_d: 'x=1, y=4',
    correct_option: 'a',
    explanation: 'Adunând: 2x=6, x=3; y=5-3=2',
  },
  {
    subject: 'algebra',
    chapter: 'Sisteme de ecuații',
    difficulty: 'medium',
    text: 'Rezolvați sistemul: 2x + y = 7, x + 2y = 8',
    option_a: 'x=2, y=3',
    option_b: 'x=3, y=2',
    option_c: 'x=1, y=5',
    option_d: 'x=4, y=-1',
    correct_option: 'a',
    explanation: 'Din prima: y=7-2x. Înlocuind: x+2(7-2x)=8, x+14-4x=8, -3x=-6, x=2, y=3',
  },
  {
    subject: 'algebra',
    chapter: 'Sisteme de ecuații',
    difficulty: 'medium',
    text: 'Rezolvați sistemul: 3x - 2y = 4, x + y = 3',
    option_a: 'x=2, y=1',
    option_b: 'x=1, y=2',
    option_c: 'x=3, y=0',
    option_d: 'x=0, y=3',
    correct_option: 'a',
    explanation: 'Din a doua: x=3-y. Înlocuind: 3(3-y)-2y=4, 9-3y-2y=4, 5y=5, y=1, x=2',
  },
  {
    subject: 'algebra',
    chapter: 'Sisteme de ecuații',
    difficulty: 'hard',
    text: 'Rezolvați sistemul: x/2 + y/3 = 1, x/3 + y/2 = 1',
    option_a: 'x=12/5, y=6/5',
    option_b: 'x=6/5, y=12/5',
    option_c: 'x=1, y=1',
    option_d: 'x=2, y=0',
    correct_option: 'a',
    explanation: 'Înmulțind cu 6: 3x+2y=6 și 2x+3y=6. Scăzând: x-y=0, x=y. Înlocuind: 5x=6, x=y=6/5',
  },

  // ALGEBRA: Funcții
  {
    subject: 'algebra',
    chapter: 'Funcții',
    difficulty: 'easy',
    text: 'Dacă f(x) = 2x + 3, atunci f(5) = ?',
    option_a: '10',
    option_b: '13',
    option_c: '8',
    option_d: '15',
    correct_option: 'b',
    explanation: 'f(5) = 2·5 + 3 = 10 + 3 = 13',
  },
  {
    subject: 'algebra',
    chapter: 'Funcții',
    difficulty: 'easy',
    text: 'Dacă f(x) = x² - 1, atunci f(3) = ?',
    option_a: '8',
    option_b: '9',
    option_c: '6',
    option_d: '10',
    correct_option: 'a',
    explanation: 'f(3) = 3² - 1 = 9 - 1 = 8',
  },
  {
    subject: 'algebra',
    chapter: 'Funcții',
    difficulty: 'medium',
    text: 'Funcția f: ℝ → ℝ, f(x) = 3x - 6 este zero în punctul:',
    option_a: 'x = 2',
    option_b: 'x = -2',
    option_c: 'x = 3',
    option_d: 'x = 6',
    correct_option: 'a',
    explanation: '3x - 6 = 0, 3x = 6, x = 2',
  },
  {
    subject: 'algebra',
    chapter: 'Funcții',
    difficulty: 'medium',
    text: 'Dacă f(x) = ax + b, f(0) = 4 și f(1) = 7, atunci a + b = ?',
    option_a: '7',
    option_b: '3',
    option_c: '11',
    option_d: '4',
    correct_option: 'a',
    explanation: 'f(0)=b=4, f(1)=a+4=7, a=3. a+b=3+4=7',
  },
  {
    subject: 'algebra',
    chapter: 'Funcții',
    difficulty: 'hard',
    text: 'Funcția f(x) = x² - 4x + 3 are valoarea minimă:',
    option_a: '-1',
    option_b: '1',
    option_c: '3',
    option_d: '0',
    correct_option: 'a',
    explanation: 'Vârful parabolei: x=-b/2a=4/2=2. f(2)=4-8+3=-1',
  },

  // ALGEBRA: Inecuații
  {
    subject: 'algebra',
    chapter: 'Inecuații',
    difficulty: 'easy',
    text: 'Rezolvați inecuația: 2x + 4 > 0',
    option_a: 'x > -2',
    option_b: 'x < -2',
    option_c: 'x > 2',
    option_d: 'x < 2',
    correct_option: 'a',
    explanation: '2x > -4, x > -2',
  },
  {
    subject: 'algebra',
    chapter: 'Inecuații',
    difficulty: 'medium',
    text: 'Rezolvați inecuația: 3x - 6 ≤ x + 2',
    option_a: 'x ≤ 4',
    option_b: 'x ≥ 4',
    option_c: 'x ≤ -4',
    option_d: 'x ≥ -4',
    correct_option: 'a',
    explanation: '3x - x ≤ 2 + 6, 2x ≤ 8, x ≤ 4',
  },
  {
    subject: 'algebra',
    chapter: 'Inecuații',
    difficulty: 'medium',
    text: 'Rezolvați inecuația: -2x + 5 > 1',
    option_a: 'x < 2',
    option_b: 'x > 2',
    option_c: 'x < -2',
    option_d: 'x > -2',
    correct_option: 'a',
    explanation: '-2x > -4, împărțind la -2 (schimbăm sensul): x < 2',
  },
  {
    subject: 'algebra',
    chapter: 'Inecuații',
    difficulty: 'hard',
    text: 'Mulțimea soluțiilor inecuației x² - 4 < 0 este:',
    option_a: '(-2, 2)',
    option_b: '(-∞, -2) ∪ (2, +∞)',
    option_c: '[-2, 2]',
    option_d: 'ℝ',
    correct_option: 'a',
    explanation: 'x²<4 ⟺ |x|<2 ⟺ -2<x<2',
  },

  // GEOMETRY: Triunghiuri
  {
    subject: 'geometry',
    chapter: 'Triunghiuri',
    difficulty: 'easy',
    text: 'Suma unghiurilor unui triunghi este:',
    option_a: '180°',
    option_b: '360°',
    option_c: '90°',
    option_d: '270°',
    correct_option: 'a',
    explanation: 'Suma unghiurilor interioare ale oricărui triunghi este întotdeauna 180°',
  },
  {
    subject: 'geometry',
    chapter: 'Triunghiuri',
    difficulty: 'easy',
    text: 'Un triunghi echilateral are toate laturile egale și fiecare unghi de:',
    option_a: '60°',
    option_b: '90°',
    option_c: '45°',
    option_d: '120°',
    correct_option: 'a',
    explanation: 'Suma unghiurilor = 180°, împărțit la 3 unghiuri egale = 60° fiecare',
  },
  {
    subject: 'geometry',
    chapter: 'Triunghiuri',
    difficulty: 'medium',
    text: 'Într-un triunghi dreptunghic, dacă un unghi ascuțit este 30°, celălalt unghi ascuțit este:',
    option_a: '60°',
    option_b: '45°',
    option_c: '30°',
    option_d: '90°',
    correct_option: 'a',
    explanation: '90° + 30° + x = 180°, x = 60°',
  },
  {
    subject: 'geometry',
    chapter: 'Triunghiuri',
    difficulty: 'medium',
    text: 'Dacă un triunghi are laturile 3, 4, 5, atunci este:',
    option_a: 'Dreptunghic',
    option_b: 'Echilateral',
    option_c: 'Isoscel',
    option_d: 'Obtuzunghic',
    correct_option: 'a',
    explanation: '3²+4²=9+16=25=5², deci satisface teorema lui Pitagora',
  },
  {
    subject: 'geometry',
    chapter: 'Triunghiuri',
    difficulty: 'hard',
    text: 'Într-un triunghi isoscel cu baza de 8 cm și latura egală de 5 cm, înălțimea pe bază este:',
    option_a: '3 cm',
    option_b: '4 cm',
    option_c: '5 cm',
    option_d: '6 cm',
    correct_option: 'a',
    explanation: 'h²+4²=5², h²=25-16=9, h=3 cm',
  },

  // GEOMETRY: Patrulater
  {
    subject: 'geometry',
    chapter: 'Patrulater',
    difficulty: 'easy',
    text: 'Care este aria unui pătrat cu latura de 6 cm?',
    option_a: '24 cm²',
    option_b: '36 cm²',
    option_c: '12 cm²',
    option_d: '48 cm²',
    correct_option: 'b',
    explanation: 'Aria pătratului = latura² = 6² = 36 cm²',
  },
  {
    subject: 'geometry',
    chapter: 'Patrulater',
    difficulty: 'easy',
    text: 'Perimetrul unui dreptunghi cu lungimea 8 cm și lățimea 5 cm este:',
    option_a: '26 cm',
    option_b: '40 cm',
    option_c: '13 cm',
    option_d: '30 cm',
    correct_option: 'a',
    explanation: 'P = 2(l + L) = 2(8 + 5) = 2·13 = 26 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Patrulater',
    difficulty: 'medium',
    text: 'Aria unui romb cu diagonalele de 6 cm și 8 cm este:',
    option_a: '24 cm²',
    option_b: '48 cm²',
    option_c: '14 cm²',
    option_d: '28 cm²',
    correct_option: 'a',
    explanation: 'Aria rombului = (d₁·d₂)/2 = (6·8)/2 = 24 cm²',
  },
  {
    subject: 'geometry',
    chapter: 'Patrulater',
    difficulty: 'medium',
    text: 'Suma unghiurilor unui patrulater convex este:',
    option_a: '360°',
    option_b: '180°',
    option_c: '270°',
    option_d: '540°',
    correct_option: 'a',
    explanation: 'Orice patrulater convex are suma unghiurilor interioare egală cu 360°',
  },
  {
    subject: 'geometry',
    chapter: 'Patrulater',
    difficulty: 'hard',
    text: 'Un trapez are bazele de 10 cm și 6 cm și înălțimea de 4 cm. Aria sa este:',
    option_a: '32 cm²',
    option_b: '40 cm²',
    option_c: '24 cm²',
    option_d: '16 cm²',
    correct_option: 'a',
    explanation: 'Aria trapezului = (B+b)/2 · h = (10+6)/2 · 4 = 8·4 = 32 cm²',
  },

  // GEOMETRY: Cerc
  {
    subject: 'geometry',
    chapter: 'Cerc',
    difficulty: 'easy',
    text: 'Aria unui cerc cu raza de 5 cm este (π ≈ 3,14):',
    option_a: '78,5 cm²',
    option_b: '31,4 cm²',
    option_c: '15,7 cm²',
    option_d: '157 cm²',
    correct_option: 'a',
    explanation: 'A = π·r² = 3,14·25 = 78,5 cm²',
  },
  {
    subject: 'geometry',
    chapter: 'Cerc',
    difficulty: 'easy',
    text: 'Circumferința unui cerc cu diametrul de 10 cm este (π ≈ 3,14):',
    option_a: '31,4 cm',
    option_b: '62,8 cm',
    option_c: '15,7 cm',
    option_d: '314 cm',
    correct_option: 'a',
    explanation: 'C = π·d = 3,14·10 = 31,4 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Cerc',
    difficulty: 'medium',
    text: 'Un unghi inscris în cerc care se sprijină pe un diametru este:',
    option_a: '90°',
    option_b: '180°',
    option_c: '45°',
    option_d: '60°',
    correct_option: 'a',
    explanation: 'Teorema unghiului inscris: un unghi inscris care se sprijină pe diametru este drept (90°)',
  },
  {
    subject: 'geometry',
    chapter: 'Cerc',
    difficulty: 'medium',
    text: 'Dacă un arc de cerc are 120° și raza este 6 cm, lungimea arcului este (π ≈ 3,14):',
    option_a: '12,56 cm',
    option_b: '6,28 cm',
    option_c: '25,12 cm',
    option_d: '18,84 cm',
    correct_option: 'a',
    explanation: 'l = (α/360°)·2πr = (120/360)·2·3,14·6 = (1/3)·37,68 = 12,56 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Cerc',
    difficulty: 'hard',
    text: 'Aria unui sector circular cu unghi de 90° și raza de 4 cm este (π ≈ 3,14):',
    option_a: '12,56 cm²',
    option_b: '50,24 cm²',
    option_c: '6,28 cm²',
    option_d: '25,12 cm²',
    correct_option: 'a',
    explanation: 'A = (α/360°)·π·r² = (90/360)·3,14·16 = (1/4)·50,24 = 12,56 cm²',
  },

  // GEOMETRY: Teorema lui Pitagora
  {
    subject: 'geometry',
    chapter: 'Teorema lui Pitagora',
    difficulty: 'easy',
    text: 'Într-un triunghi dreptunghic cu catetele 3 cm și 4 cm, ipotenuza este:',
    option_a: '5 cm',
    option_b: '7 cm',
    option_c: '6 cm',
    option_d: '12 cm',
    correct_option: 'a',
    explanation: 'c² = 3² + 4² = 9 + 16 = 25, c = 5 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Teorema lui Pitagora',
    difficulty: 'easy',
    text: 'Într-un triunghi dreptunghic cu ipotenuza 13 cm și o catetă de 5 cm, cealaltă catetă este:',
    option_a: '12 cm',
    option_b: '8 cm',
    option_c: '10 cm',
    option_d: '11 cm',
    correct_option: 'a',
    explanation: 'b² = 13² - 5² = 169 - 25 = 144, b = 12 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Teorema lui Pitagora',
    difficulty: 'medium',
    text: 'Diagonala unui pătrat cu latura de 4 cm este:',
    option_a: '4√2 cm',
    option_b: '8 cm',
    option_c: '4 cm',
    option_d: '2√2 cm',
    correct_option: 'a',
    explanation: 'd² = 4² + 4² = 32, d = √32 = 4√2 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Teorema lui Pitagora',
    difficulty: 'medium',
    text: 'Înălțimea unui triunghi echilateral cu latura de 6 cm este:',
    option_a: '3√3 cm',
    option_b: '6 cm',
    option_c: '3 cm',
    option_d: '√3 cm',
    correct_option: 'a',
    explanation: 'h² = 6² - 3² = 36 - 9 = 27, h = √27 = 3√3 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Teorema lui Pitagora',
    difficulty: 'hard',
    text: 'Un dreptunghi are diagonala de 10 cm și o latură de 6 cm. Cealaltă latură este:',
    option_a: '8 cm',
    option_b: '4 cm',
    option_c: '7 cm',
    option_d: '√136 cm',
    correct_option: 'a',
    explanation: 'b² = 10² - 6² = 100 - 36 = 64, b = 8 cm',
  },

  // GEOMETRY: Arii și perimetre
  {
    subject: 'geometry',
    chapter: 'Arii și perimetre',
    difficulty: 'easy',
    text: 'Perimetrul unui triunghi echilateral cu latura de 7 cm este:',
    option_a: '21 cm',
    option_b: '14 cm',
    option_c: '28 cm',
    option_d: '49 cm',
    correct_option: 'a',
    explanation: 'P = 3·l = 3·7 = 21 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Arii și perimetre',
    difficulty: 'medium',
    text: 'Aria unui triunghi cu baza de 10 cm și înălțimea de 6 cm este:',
    option_a: '30 cm²',
    option_b: '60 cm²',
    option_c: '15 cm²',
    option_d: '120 cm²',
    correct_option: 'a',
    explanation: 'A = (b·h)/2 = (10·6)/2 = 30 cm²',
  },
  {
    subject: 'geometry',
    chapter: 'Arii și perimetre',
    difficulty: 'medium',
    text: 'Un dreptunghi are aria de 48 cm² și lungimea de 8 cm. Lățimea sa este:',
    option_a: '6 cm',
    option_b: '4 cm',
    option_c: '12 cm',
    option_d: '40 cm',
    correct_option: 'a',
    explanation: 'l = A/L = 48/8 = 6 cm',
  },
  {
    subject: 'geometry',
    chapter: 'Arii și perimetre',
    difficulty: 'hard',
    text: 'Aria unui triunghi dreptunghic cu catetele 5 cm și 12 cm este:',
    option_a: '30 cm²',
    option_b: '60 cm²',
    option_c: '65 cm²',
    option_d: '26 cm²',
    correct_option: 'a',
    explanation: 'A = (c₁·c₂)/2 = (5·12)/2 = 30 cm²',
  },

  // ARITHMETIC: Mulțimi de numere
  {
    subject: 'arithmetic',
    chapter: 'Mulțimi de numere',
    difficulty: 'easy',
    text: 'Care dintre următoarele numere este irațional?',
    option_a: '√2',
    option_b: '√4',
    option_c: '√9',
    option_d: '√16',
    correct_option: 'a',
    explanation: '√2 nu poate fi scris ca fracție, deci este irațional. √4=2, √9=3, √16=4 sunt raționale',
  },
  {
    subject: 'arithmetic',
    chapter: 'Mulțimi de numere',
    difficulty: 'easy',
    text: 'Mulțimea numerelor naturale include:',
    option_a: '0, 1, 2, 3, ...',
    option_b: '..., -2, -1, 0, 1, 2, ...',
    option_c: 'Toate fracțiile',
    option_d: 'Toate numerele reale',
    correct_option: 'a',
    explanation: 'Numerele naturale sunt: 0, 1, 2, 3, ... (numere întregi nenegative)',
  },
  {
    subject: 'arithmetic',
    chapter: 'Mulțimi de numere',
    difficulty: 'medium',
    text: 'Care este cel mai mare număr întreg mai mic decât √50?',
    option_a: '7',
    option_b: '6',
    option_c: '8',
    option_d: '5',
    correct_option: 'a',
    explanation: '√49=7 și √50>7, deci cel mai mare întreg mai mic decât √50 este 7',
  },
  {
    subject: 'arithmetic',
    chapter: 'Mulțimi de numere',
    difficulty: 'medium',
    text: 'Câte numere prime sunt mai mici decât 20?',
    option_a: '8',
    option_b: '7',
    option_c: '9',
    option_d: '6',
    correct_option: 'a',
    explanation: 'Numerele prime < 20: 2,3,5,7,11,13,17,19 — sunt 8 numere prime',
  },

  // ARITHMETIC: Operații cu fracții
  {
    subject: 'arithmetic',
    chapter: 'Operații cu fracții',
    difficulty: 'easy',
    text: 'Calculați: 1/2 + 1/3',
    option_a: '5/6',
    option_b: '2/5',
    option_c: '2/6',
    option_d: '1/6',
    correct_option: 'a',
    explanation: '1/2 + 1/3 = 3/6 + 2/6 = 5/6',
  },
  {
    subject: 'arithmetic',
    chapter: 'Operații cu fracții',
    difficulty: 'easy',
    text: 'Calculați: 3/4 - 1/4',
    option_a: '2/4',
    option_b: '1/2',
    option_c: '1/4',
    option_d: '3/8',
    correct_option: 'b',
    explanation: '3/4 - 1/4 = 2/4 = 1/2',
  },
  {
    subject: 'arithmetic',
    chapter: 'Operații cu fracții',
    difficulty: 'medium',
    text: 'Calculați: 2/3 × 3/4',
    option_a: '1/2',
    option_b: '6/12',
    option_c: '2/4',
    option_d: '1/3',
    correct_option: 'a',
    explanation: '2/3 × 3/4 = 6/12 = 1/2',
  },
  {
    subject: 'arithmetic',
    chapter: 'Operații cu fracții',
    difficulty: 'medium',
    text: 'Calculați: 5/6 ÷ 5/3',
    option_a: '1/2',
    option_b: '25/18',
    option_c: '1/3',
    option_d: '3/2',
    correct_option: 'a',
    explanation: '5/6 ÷ 5/3 = 5/6 × 3/5 = 15/30 = 1/2',
  },
  {
    subject: 'arithmetic',
    chapter: 'Operații cu fracții',
    difficulty: 'hard',
    text: 'Simplificați: (2/3 + 1/6) ÷ (3/4 - 1/2)',
    option_a: '10/3',
    option_b: '5/6',
    option_c: '1/2',
    option_d: '2',
    correct_option: 'a',
    explanation: 'Numărător: 4/6+1/6=5/6. Numitor: 3/4-2/4=1/4. Rezultat: 5/6 ÷ 1/4 = 5/6 × 4 = 20/6 = 10/3',
  },

  // ARITHMETIC: Puteri și radicali
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'easy',
    text: 'Calculați: 2⁵',
    option_a: '32',
    option_b: '16',
    option_c: '64',
    option_d: '25',
    correct_option: 'a',
    explanation: '2⁵ = 2·2·2·2·2 = 32',
  },
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'easy',
    text: 'Calculați: √144',
    option_a: '12',
    option_b: '11',
    option_c: '13',
    option_d: '14',
    correct_option: 'a',
    explanation: '12² = 144, deci √144 = 12',
  },
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'medium',
    text: 'Simplificați: √75',
    option_a: '5√3',
    option_b: '3√5',
    option_c: '15√3',
    option_d: '25√3',
    correct_option: 'a',
    explanation: '√75 = √(25·3) = 5√3',
  },
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'medium',
    text: 'Calculați: 3² + 4²',
    option_a: '25',
    option_b: '7',
    option_c: '49',
    option_d: '14',
    correct_option: 'a',
    explanation: '3² + 4² = 9 + 16 = 25',
  },
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'hard',
    text: 'Calculați: (√3 + 1)(√3 - 1)',
    option_a: '2',
    option_b: '4',
    option_c: '√3',
    option_d: '0',
    correct_option: 'a',
    explanation: '(√3)² - 1² = 3 - 1 = 2 (diferența de pătrate)',
  },
  {
    subject: 'arithmetic',
    chapter: 'Puteri și radicali',
    difficulty: 'hard',
    text: 'Simplificați: √(12) + √(27)',
    option_a: '5√3',
    option_b: '3√3',
    option_c: '√39',
    option_d: '9√3',
    correct_option: 'a',
    explanation: '√12=2√3, √27=3√3, suma=5√3',
  },

  // ARITHMETIC: Proporții
  {
    subject: 'arithmetic',
    chapter: 'Proporții',
    difficulty: 'easy',
    text: 'Dacă 3/x = 6/10, atunci x = ?',
    option_a: '5',
    option_b: '4',
    option_c: '6',
    option_d: '3',
    correct_option: 'a',
    explanation: '3·10 = 6·x, 30 = 6x, x = 5',
  },
  {
    subject: 'arithmetic',
    chapter: 'Proporții',
    difficulty: 'medium',
    text: 'Dacă a/b = 3/4 și a + b = 35, atunci a = ?',
    option_a: '15',
    option_b: '20',
    option_c: '12',
    option_d: '21',
    correct_option: 'a',
    explanation: 'a=3k, b=4k, 3k+4k=35, 7k=35, k=5, a=15',
  },
  {
    subject: 'arithmetic',
    chapter: 'Proporții',
    difficulty: 'medium',
    text: 'Un produs costă 120 lei. Dacă prețul crește cu 25%, noul preț este:',
    option_a: '150 lei',
    option_b: '145 lei',
    option_c: '130 lei',
    option_d: '160 lei',
    correct_option: 'a',
    explanation: '120 + 120·25/100 = 120 + 30 = 150 lei',
  },
  {
    subject: 'arithmetic',
    chapter: 'Proporții',
    difficulty: 'hard',
    text: 'Dacă 5 muncitori termină o lucrare în 12 zile, câte zile vor fi necesare pentru 10 muncitori?',
    option_a: '6 zile',
    option_b: '24 zile',
    option_c: '10 zile',
    option_d: '8 zile',
    correct_option: 'a',
    explanation: 'Proporție inversă: 5·12 = 10·x, x = 60/10 = 6 zile',
  },
];

app.logger.info({ count: questions.length }, 'Inserting seed questions');

try {
  await app.db.insert(schema.questions).values(questions);
  app.logger.info({ count: questions.length }, 'Questions inserted successfully');
} catch (error) {
  app.logger.error({ err: error }, 'Failed to insert questions');
  process.exit(1);
}

process.exit(0);
